# This file was generated by GoReleaser. DO NOT EDIT.
cask "bore" do
  name "bore"
  desc "Blazing fast, free TCP tunnel that exposes your localhost to the world"
  homepage "https://trybore.com/"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bore"

  on_macos do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "a91cf6b94bec812d7b5b5aa41cd35dab34b4db7410661fd4282adb81bbce6501"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "f8f1e21b85074f95f126180b201f289f41dc4508b65df7635764d2f0603661c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "5117975ae8c54a4c59007caf576f7301c508d8c5c1207b757cf190c9659c2a70"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "6673da838594e9d99517b4479b3f1531952f7acddad30418399d2d5f50b61204"
    end
  end

  # No zap stanza required
end
