# This file was generated by GoReleaser. DO NOT EDIT.
cask "bore" do
  name "bore"
  desc "Blazing fast, free TCP tunnel that exposes your localhost to the world"
  homepage "https://trybore.com/"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bore"

  on_macos do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "ad0900d5f4c9ff94492c90777b2be4801496f3b289d039b0c7fef9a4cf5f749c"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "ee9717f110d7bf1f7ecdd5cf1eb242329dc1aa5aa1c7cc07aede871e57b893d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "109051b7d8ed030c2a1f869213199bbb62380c551c5a1d81d56fcab44566d1fe"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "a8cb6b185fd5a12b94feada7656dd41434ed498b9237dd88ccc421de9c7fbfa4"
    end
  end

  # No zap stanza required
end
