# This file was generated by GoReleaser. DO NOT EDIT.
cask "bore" do
  name "bore"
  desc "Blazing fast, free TCP tunnel that exposes your localhost to the world"
  homepage "https://trybore.com/"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bore"

  on_macos do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "98e8c252e28cf8d67e2f42b52c9236d1d923ef074fafbb76d84f06bd8de807e3"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "85cd22006832c0a3403b22bfa98bdf2df5ac75625219f72d694a1b51cbf4955d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_amd64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "b29bc995e2135b3d07a7726fb003ca6df40fa8a0a5e40d5522e65f94691077e3"
    end
    on_arm do
      url "https://github.com/aditya-ds-1806/bore/releases/download/v#{version}/bore_#{version}_linux_arm64.tar.gz",
        verified: "github.com/aditya-ds-1806/bore/"
      sha256 "6ad26f148a8381cc78aebf1f52c244ddca0214351b271a3193a71a1a0ab1f692"
    end
  end

  # No zap stanza required
end
